clean:
	rm -f Assignments/Week0/C/*.c
	rm -f Assignments/Week0/C/*.o
	rm -f Assignments/Week0/C/*.x
	rm -f Assignments/Week1/C/*.c
	rm -f Assignments/Week1/C/*.o
	rm -f Assignments/Week1/C/*.x
	rm -f Assignments/Week1/C/data/*
	rm -f Assignments/Week1/C/*.c
	rm -f Assignments/Week1/C/*.o
	rm -f Assignments/Week1/C/*.x
	rm -f Assignments/Week1/C/data/*
	rm -f Assignments/Week2/C/*.c
	rm -f Assignments/Week2/C/*.o
	rm -f Assignments/Week2/C/*.x
	rm -f Assignments/Week2/C/data/*
	rm -f Assignments/Week3/C/*.c
	rm -f Assignments/Week3/C/*.o
	rm -f Assignments/Week3/C/*.x
	rm -f Assignments/Week3/C/data/*
	rm -f Assignments/Week4/C/*.c
	rm -f Assignments/Week4/C/*.o
	rm -f Assignments/Week4/C/*.x
	rm -f Assignments/Week4/C/data/*
